-keepattributes Signature,InnerClasses,EnclosingMethod
-keep class kotlinx.serialization.** { *; }
-keepclassmembers class com.zeus.code.model.** { *; }
-dontwarn org.eclipse.jgit.**
-dontwarn org.slf4j.**
